version: "3.7"

services:
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: fabio
      POSTGRES_PASSWORD: smartbrain
      POSTGRES_URL: postgres://fabio:smartbrain@postgres:5432/multitasker
      POSTGRES_DB: multitasker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Backhand API
  multitasker-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/Multitasker-api
    command: npm start
    working_dir: /usr/src/Multitasker-api
    ports:
      - "80:8080"
      - "443:4433"
    links:
      - postgres
      - redis
    environment:
      POSTGRES_URI: postgres://fabio:smartbrain@postgres:5432/multitasker
      REDIS_URI: redis://redis:6379
      JWT_SECRET: jsonWebTokenSecret
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  # 3.7 version of docker, with adminer ↓
  # Postgres database
  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: multitasker
  #     POSTGRES_USER: fabio
  #     POSTGRES_PASSWORD: learning
  #     POSTGRES_HOST: postgres
  #   build: ./postgres
  #   ports:
  #     - "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 6000:6000

  # redis
