version: "3.7"

services:
  # Backhand API
  multitasker-api:
    container_name: backend
    build: ./
    environment:
      POSTGRES_URI: postgres://fabio:secret@postgres:5432/multitasker
      REDIS_URI: redis://redis:6379
      JWT_SECRET: jsonWebTokenSecret
    links:
      - postgres
      - redis
    command: npm start
    working_dir: /usr/src/Multitasker-api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - .:/usr/src/Multitasker-api

  # Postgres database
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: multitasker
      POSTGRES_USER: fabio
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 6000:6000

  # redis
  redis:
    image: redis
    ports:
      - 6379:6379
