version: '3.7'

services:
  # Backhand API
  smart-brain-api:
    container_name: backend
    build: ./
    environment:
      POSTGRES_URI: postgres://fabio:secret@postgres:5432/MULTITASKER-API
      REDIS_URI: redis://redis:6379
      JWT_SECRET: jsonWebTokenSecret
    links:
      - postgres
      - redis
    command: npm start
    working_dir: /usr/src/MULTITASKER-API
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/MULTITASKER-API

  # Postgres database
  postgres:
    restart: always
    environment:
      POSTGRES_DB: MULTITASKER-API
      POSTGRES_USER: fabio
      POSTGRES_PASSWORD: secret   
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # redis
  redis:
    image: redis
    ports:
      - 6379:6379